version: 2.1
jobs:
  build:
    working_directory: ~/webext-pixiv-toolkit
    docker:
      - image: cimg/node:16.18.0
    steps:
      - checkout
      #- run:
      #    name: update-npm
      #    command: 'sudo npm install -g npm@latest'
      # - run:
      #    name: install-yarn
      #    command: 'sudo npm install -g yarn@1.22.19'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: "Install npm packages"
          command: "yarn install"
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: "Rebuild node-sass"
          command: "npm rebuild node-sass"
      - run:
          name: "Build extension for Chrome"
          command: "yarn build"
      - run:
          name: "Build exntesion for Firefox"
          command: "yarn build:firefox"
      - run:
          name: "Create artifacts"
          command: |
            tar -cvzf ./chrome.tar.gz ./dist/chrome/
            tar -cvzf ./firefox.tar.gz ./dist/firefox/
      - store_artifacts:
          path: ./chrome.tar.gz
      - store_artifacts:
          path: ./firefox.tar.gz
