version: 2.1
jobs:
  build:
    working_directory: ~/webext-pixiv-toolkit
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "Install npm packages"
          command: "npm install"
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Rebuild node-sass"
          command: "npm rebuild node-sass"
      - run:
          name: "Build extension for Chrome"
          command: "npm run build"
      - run:
          name: "Build exntesion for Firefox"
          command: "npm run build:firefox"
      - run:
          name: "Create artifacts"
          command: |
            tar -cvzf ./chrome.tar.gz ./dist/chrome/
            tar -cvzf ./firefox.tar.gz ./dist/firefox/
      - store_artifacts:
          path: ./chrome.tar.gz
      - store_artifacts:
          path: ./firefox.tar.gz
